function validateERAPipelineInputs(impulseResponse, svdTolerance, fs, ...
    nRows, nColumns, opts)
% VALIDATEERAPIPELINEINPUTS  Centralised input validation for the
%                            ERA pipeline.
%
% DESCRIPTION:
%   Performs all user input validation in a single pass at the entry
%   point of the ERA pipeline. Called from eigensystemRealisation()
%   before any subfunction is invoked.
%
% INPUTS:
%   impulseResponse - [double, N x 1]   Raw impulse response signal.
%   svdTolerance    - [double, scalar]  SVD truncation control.
%   fs              - [double, scalar]  Sample rate in Hz.
%   nRows           - [integer, scalar] Resolved Hankel rows.
%   nColumns        - [integer, scalar] Resolved Hankel columns.
%   opts            - [struct]          Resolved configuration.
%
% OUTPUTS:
%   None. Throws on any validation failure.
%
% AUTHOR:   -
% DATE:     June 2026
% VERSION:  1.0

%% Raw input attribute checks

validateattributes(impulseResponse, {'double'}, ...
    {'vector', 'real', 'nonempty', 'finite'}, ...
    'eigensystemRealisation', 'impulseResponse');

validateattributes(svdTolerance, {'double'}, ...
    {'scalar', 'real', 'positive', 'finite'}, ...
    'eigensystemRealisation', 'svdTolerance');

validateattributes(fs, {'numeric'}, ...
    {'scalar', 'real', 'positive', 'finite'}, ...
    'eigensystemRealisation', 'fs');

%% Resolved Hankel dimension checks

validateattributes(nRows, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'nonempty'}, ...
    'eigensystemRealisation', 'nRows');

validateattributes(nColumns, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'nonempty'}, ...
    'eigensystemRealisation', 'nColumns');

%% Opts struct attribute checks

validateattributes(opts, {'struct'}, {'nonempty'}, ...
    'eigensystemRealisation', 'opts');

% Pipeline control flags
validateattributes(opts.validateInputs, {'logical', 'numeric'}, ...
    {'scalar', 'binary'}, ...
    'eigensystemRealisation', 'opts.validateInputs');

validateattributes(opts.returnDebug, {'logical', 'numeric'}, ...
    {'scalar', 'binary'}, ...
    'eigensystemRealisation', 'opts.returnDebug');

% Hankel options
validateattributes(opts.hankelSignalIndex, {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, ...
    'eigensystemRealisation', 'opts.hankelSignalIndex');

% Modal filtering options
validateattributes(opts.filterUnstable, {'logical', 'numeric'}, ...
    {'scalar', 'binary'}, ...
    'eigensystemRealisation', 'opts.filterUnstable');

validateattributes(opts.filterNegativeDamp, {'logical', 'numeric'}, ...
    {'scalar', 'binary'}, ...
    'eigensystemRealisation', 'opts.filterNegativeDamp');

validateattributes(opts.filterNegativeFreq, {'logical', 'numeric'}, ...
    {'scalar', 'binary'}, ...
    'eigensystemRealisation', 'opts.filterNegativeFreq');

validateattributes(opts.filterOverdamped, {'logical', 'numeric'}, ...
    {'scalar', 'binary'}, ...
    'eigensystemRealisation', 'opts.filterOverdamped');

validateattributes(opts.dampingThreshold, {'double'}, ...
    {'scalar', 'real', 'positive', 'finite', '<=', 1}, ...
    'eigensystemRealisation', 'opts.dampingThreshold');

%% svdTolerance mode-specific check
% In count mode (>= 1), tolerance must be integer-valued
if svdTolerance >= 1
    assert(svdTolerance == floor(svdTolerance), ...
        'eigensystemRealisation:nonIntegerSvdCount', ...
        ['svdTolerance = %.4f. Values >= 1 are interpreted as mode ' ...
         'counts and must be integer-valued.'], svdTolerance);
end

%% Cross-parameter consistency checks
nSamples = numel(impulseResponse);

% Hankel dimensions must accommodate the one-sample shift for H(1)
assert(nSamples >= nRows + nColumns, ...
    'eigensystemRealisation:insufficientData', ...
    ['Signal length (%d) is insufficient for the requested Hankel ' ...
     'dimensions (%d rows + %d columns). Minimum required: %d ' ...
     'samples (nRows + nColumns) to accommodate the shifted Hankel ' ...
     'matrix H(1).'], nSamples, nRows, nColumns, nRows + nColumns);

% Hankel signal index must leave samples for Hankel construction
assert(opts.hankelSignalIndex < nSamples, ...
    'eigensystemRealisation:invalidHankelIndex', ...
    ['opts.hankelSignalIndex (%d) exceeds signal length (%d). ' ...
     'No samples remain for Hankel construction.'], ...
    opts.hankelSignalIndex, nSamples);

% In count mode, svdTolerance modes (doubled internally) must not exceed
% the available rank of the Hankel matrix
if svdTolerance >= 1
    requestedRank = 2 * svdTolerance;
    availableRank = min(nRows, nColumns);
    assert(requestedRank <= availableRank, ...
        'eigensystemRealisation:truncationExceedsRank', ...
        ['svdTolerance (%d) requests %d modes (after conjugate pair ' ...
         'doubling) but the Hankel matrix has maximum rank %d ' ...
         '(min of nRows=%d and nColumns=%d).'], ...
        svdTolerance, requestedRank, availableRank, nRows, nColumns);
end

end